export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_FROM_STORE = 'FETCH_FROM_STORE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
